import { Metadata } from "next";
import Heading from "../components/copy";
import Wrapper from "../components/wrapper";

export const metadata: Metadata = {
  title: "projects / psrth.sh",
  description: "Generated by create next app",
};

function Projects() {
  return (
    <Wrapper>
      <Heading>Projects</Heading>
    </Wrapper>
  );
}

export default Projects;
