import type { Metadata } from "next";
import localFont from "next/font/local";
import { unstable_ViewTransition as ViewTransition } from "react";

import "./globals.css";
import "./styles/syntax-highlighting.css";

import Header from "./components/header";
import Footer from "./components/footer";

const soehne = localFont({
  src: [
    {
      path: "../../public/fonts/soehne-buch.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/soehne-kraftig.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/soehne-kraftig.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-soehne",
});

const tiempos = localFont({
  src: "../../public/fonts/tiempos-text-regular.woff2",
  weight: "400",
  variable: "--font-tiempos",
});

export const metadata: Metadata = {
  title: "home / psrth.sh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${soehne.variable} ${tiempos.variable} antialiased`}>
        <Header />
        <main className="flex flex-col w-[100vw] lg:w-[1024px] mx-auto mt-25 bg-white">
          <div className="page-content">
            <ViewTransition>{children}</ViewTransition>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
