import Link from "next/link";
import { Metadata } from "next";

import { notes } from "./content/notes";

import Heading from "../components/copy";
import Wrapper from "../components/wrapper";

export const metadata: Metadata = {
  title: "notes / psrth.sh",
  description: "Generated by create next app",
};

function Notes() {
  return (
    <Wrapper>
      <Heading>Notes</Heading>

      {/* notes table - header */}
      <div className="hidden md:flex flex-row gap-16 mt-10">
        <p className="text-[16px]/7 md:text-[18px]/8 font-regular text-[var(--color-light-gray)] w-[50px]">
          date
        </p>
        <p className="text-[16px]/7 md:text-[18px]/8 font-regular text-[var(--color-light-gray)]">
          title
        </p>
      </div>
      <div className="hidden md:flex w-full h-[2px] bg-[var(--color-light-gray)] opacity-20 mt-3" />

      {/* notes table - core */}
      {(() => {
        const shownYears = new Set();
        return notes.map((note) => {
          const year = note.date.split("-")[0];
          const shouldShowYear = !shownYears.has(year);
          if (shouldShowYear) {
            shownYears.add(year);
          }
          return (
            <div className="flex flex-col" key={note.date}>
              <Link href={note.link}>
                <div className="flex flex-col md:flex-row gap-2 md:gap-16 py-3">
                  <p
                    className={`text-[16px]/7 md:text-[18px]/8 font-regular text-[var(--color-light-gray)] w-[50px] ${
                      shouldShowYear ? "mt-10 md:mt-0" : ""
                    }`}
                  >
                    {shouldShowYear ? year : ""}
                  </p>
                  <p className="text-[16px]/7 md:text-[18px]/8 font-regular text-[var(--color-gray)] overflow-hidden text-ellipsis whitespace-nowrap max-w-[300px] md:max-w-[500px]">
                    {note.title}
                  </p>
                </div>
              </Link>
              <div className="w-full h-[2px] bg-[var(--color-light-gray)] opacity-20" />
            </div>
          );
        });
      })()}
    </Wrapper>
  );
}

export default Notes;
