import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.master}>
      <Head>
        <title>Parth Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.card}>
        {/* HEADER SECTION */}
        <div className={styles.header}>
          <div className={styles.header__main}>
            <img 
              src="https://avatars.githubusercontent.com/u/45586386?v=4" 
              className={styles.header__pp} 
            />
            <div className={styles.header__title}>Parth Sharma</div>
          </div>

          <div className={styles.header__navbar}>
            <div className={styles.header__navlink}>Blog</div>
            <div className={styles.header__navlink}>Resume</div>
            <div className={styles.header__navlink}>Portfolio</div>
          </div>
        </div>

        {/* DIVIDER */}
        <div className={styles.divider} />
      </div>
    </div>
  )
}
